version: '3.3'
services:

  db:
     image: postgres:14.1-alpine
     environment:
     - POSTGRES_DB=schematron
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=Passw0rd
     ports:
     - 5432:5432
     volumes:
     - db:/var/lib/postgresql/data
     restart: unless-stopped
     networks:
     - schematron

  rabbitmq:
    image: postgres:14.1-alpine
    ports:
    - "5672:5672"
    - "15672:15672"
    - "15674:15674"
    environment:
    - RABBITMQ_DEFAULT_USER=admin
    - RABBITMQ_DEFAULT_PASS=Passw0rd
#    volumes:
#        - .docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
#        - .docker-conf/rabbitmq/log/:/var/log/rabbitmq
    networks:
    - schematron

  keycloak:
    image: quay.io/keycloak/keycloak:19.0.3
    restart: always
    ports:
    - "8081:8080"
    environment:
    - KEYCLOAK_ADMIN=admin
    - KEYCLOAK_ADMIN_PASSWORD=Passw0rd
    command: start-dev
    restart: unless-stopped
    networks:
    - schematron

  api:
     build:
        context: ./schematron-api/schematron-api-server
        dockerfile: Dockerfile
     volumes:
     - ./schematron-api/schematron-server:/var/www
#     ports:
#     - 8080:8080
     links:
     - db
     - rabbitmq
     restart: unless-stopped
     networks:
     - schematron

  web:
    build:
       context: ./schematron-web/schematron-web-app
       dockerfile: Dockerfile
    restart: always
    volumes:
    - ./schematron-web/schematron-web-app:/var/www
    ports:
    - 4200:4200
#     links:
#     - api
    restart: unless-stopped
    networks:
    - schematron

volumes:
   db:
      driver: local
   web:
      driver: local

networks:
  schematron:
    driver: bridge