openapi: 3.0.3

info:
   title: Schematron API
   description: Schematron API
   termsOfService: http://api.schematron.bishub.cy/terms/
   contact:
      name: API Support
      url: http://api.schematron.bishub.cy/support
      email: support@bishub.cy
   license:
      name: Bishub Limited
      url: https://www.apache.org/licenses/LICENSE-2.0.html
   version: 0.0.1

tags:
   - name: Document
     description: Document operations
   - name: Namespace
     description: Namespace operations
   - name: Element
     description: Element operations
   - name: Attribute
     description: Attribute operations

servers:
-  url: http://localhost:8080
   description: Development server

components:
   securitySchemes:
      BEARER:
         $ref: './components/securitySchemes/BEARER.yaml'

paths:
   /folder:
      $ref: './paths/Folder/FolderList.yaml'
   /folder/{FolderId}:
      $ref: './paths/Folder/Folder.yaml'
   /document:
      $ref: './paths/Document/DocumentList.yaml'
   /document/{DocumentId}:
      $ref: './paths/Document/Document.yaml'
   /namespace:
      $ref: './paths/Namespace/NamespaceList.yaml'
   /namespace/{NamespaceId}:
      $ref: './paths/Namespace/Namespace.yaml'
   /element:
      $ref: './paths/Element/ElementList.yaml'
   /element/{ElementId}:
      $ref: './paths/Element/Element.yaml'
   /attribute:
      $ref: './paths/Attribute/AttributeList.yaml'
   /attribute/{AttributeId}:
      $ref: './paths/Attribute/Attribute.yaml'