/**
 * Schematron API
 * Schematron API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@bishub.cy
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Document } from './document';


export class DocumentList { 
    items?: Array<Document>;
    itemsTotalCount?: number;
    itemPageCount?: number;
    pageCurrent?: number;
    pageSize?: number;
    pageCount?: number;
}
