/**
 * Schematron API
 * Schematron API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@bishub.cy
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Element } from './element';
import { Namespace } from './namespace';


/**
 * Document Model
 */
export class Document { 
    id?: number;
    name?: string;
    namespaces?: Array<Namespace>;
    element?: Element;
    content?: string;
    created?: string;
    updated?: string;
}
