/**
 * Schematron API
 * Schematron API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@bishub.cy
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Attribute } from './attribute';
import { Document } from './document';
import { Namespace } from './namespace';


/**
 * Element Model
 */
export class Element { 
    id?: number;
    name?: string;
    content?: string;
    document?: Document;
    namespace?: Namespace;
    attributes?: Array<Attribute>;
    parent?: Element;
    children?: Array<Element>;
    created?: string;
    updated?: string;
}
