/**
 * Schematron API
 * Schematron API
 *
 * The version of the OpenAPI document: 0.0.1
 * Contact: support@bishub.cy
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Document } from './document';


/**
 * Folder Model
 */
export class Folder { 
    id?: number;
    parent?: Folder;
    name?: string;
    children?: Array<Folder>;
    documents?: Array<Document>;
    created?: string;
    updated?: string;
}
