export * from './attribute.service';
import { AttributeService } from './attribute.service';
export * from './document.service';
import { DocumentService } from './document.service';
export * from './element.service';
import { ElementService } from './element.service';
export * from './folder.service';
import { FolderService } from './folder.service';
export * from './namespace.service';
import { NamespaceService } from './namespace.service';
export const APIS = [AttributeService, DocumentService, ElementService, FolderService, NamespaceService];
